/*
 * This source file was generated by the Gradle 'init' task
 */
package com.arka.arkahv;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        ArkahvApplication classUnderTest = new ArkahvApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
