/*
 * This source file was generated by the Gradle 'init' task
 */
package com.arka.arkahv;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ArkaApplicationTest {
    @Test
    void contextLoads() {
    }
}
