/*
 * This source file was generated by the Gradle 'init' task
 */
package com.arka.arkahv;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ArkahvApplication {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println(new ArkahvApplication().getGreeting());
        SpringApplication.run(ArkahvApplication.class, args);
    }
}
