services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: arkabdprueba
      # MYSQL_USER: root
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    networks:
      - springboot-mysql

  app:
    build: .
    container_name: springboot_app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/arkabdprueba?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
     # SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - springboot-mysql

networks:
  springboot-mysql:
    driver: bridge
